# task-build-image.yml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    tag: latest

inputs:
  - name: git-sources
  - name: version-backend

outputs:
  - name: image

params:
  CONTEXT: git-sources
  DOCKERFILE: git-sources/src/main/docker/Dockerfile.jvm
  IMAGE_NAME: my-quarkus-app
  IMAGE_TAG: latest
  REGISTRY: ((composants.docker_repo))
  USERNAME: ((composants.docker_username))
  PASSWORD: ((composants.docker_token))

run:
  path: /bin/sh
  args:
    - -c
    - |
      # Build the Docker image
      docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:${IMAGE_TAG} ${CONTEXT}

      
