platform: linux
image_resource:
  type: registry-image
  source:
    repository: sonarsource/sonar-scanner-cli
inputs:
  - name: git-ci
run:
  path: sh
  args:
    - -exc
    - |
      cd git-ci
      # Vérifier les variables d'environnement
      echo "SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}"
      echo "SONAR_SOURCES=${SONAR_SOURCES}"
      echo "SONAR_LOGIN=${SONAR_LOGIN}"
      
      # Copier le fichier template et remplacer les variables d'environnement
      envsubst < sonar-scanner.properties > sonar-scanner.properties
      
      # Exécuter le scanner
      echo "Starting SonarQube Scanner"
      sonar-scanner -X
