
platform: linux
image_resource:
  type: registry-image
  source: {repository: sonarsource/sonar-scanner-cli}
inputs:
  - name: git-sources
params:
run:
  path: sh
  args:
     - -exc
     - |
       cd git-sources
       sonar-scanner \
          -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
          -Dsonar.sources=${SONAR_SOURCES} \
          -Dsonar.host.url=${SONAR_HOST_URL} \
          -Dsonar.login=${SONAR_LOGIN}